name: Updater

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r ./python/requirements.txt
          
      - name: push blogs
        run: python3 ./python/dailyNews.py -f FeedList.json -i blogs -o ./states/blogs
      - name: push CVEs
        run: python3 ./python/dailyNews.py -f FeedList.json -i cve -o ./states/cve
      - name: push advisories
        run: python3 ./python/dailyNews.py -f FeedList.json -i advisories -o ./states/advisories
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: websecnews
          commit_user_email: websecnews@local
          commit_author: websecnews <websecnews@local>
          
      - name: push cve RSS
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
        run: python3 python/CVE_RSS.py $GITHUBTOKEN

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: websecnews
          commit_user_email: websecnews@local
          commit_author: websecnews <websecnews@local>
